version: "3"

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: embed-many-with-bson-id
        volumes:
            - ./:/var/www/symfony
            - ./var/log/:/var/www/symfony/var/log:delegated
            - ./var/cache:/var/www/symfony/var/cache:delegated
        depends_on:
            - mongo
        links:
            - mongo
        networks:
            - code-network

    mongo:
        image: mongo:4.0
        ports:
            - "27018:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: dbuser
            MONGO_INITDB_ROOT_PASSWORD: dbpw
            MONGO_INITDB_DATABASE: test
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
